# Generated by Django 3.1.2 on 2020-10-11 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=128)),
                ('instituica', models.CharField(max_length=64)),
                ('cep', models.CharField(max_length=9)),
                ('endereco', models.CharField(max_length=256)),
                ('bairro', models.CharField(max_length=64)),
                ('cidade', models.CharField(max_length=64)),
                ('descricao', models.TextField()),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
