version: "3.3"

services:
    database:
        container_name: voluntarios_database
        image: postgres
        restart: always
        volumes:
            - ./.pgdata:/var/lib/postgresql/data
        environment:
            - LC_ALL=C.UTF-8
            - POSTGRES_PASSWORD=postgreSQL
            - POSTGRES_USER=postgres
        ports:
            - 5434:5432

