version: "3.8"

services:
    database:
        container_name: voluntarios_database
        image: postgres
        restart: always
        volumes:
            - ./.pgdata:/var/lib/postgresql/data
        environment:
            - LC_ALL=C.UTF-8
            - POSTGRES_DB=voluntarios
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        ports:
            - 5434:5432

    web:
        container_name: voluntarios_web
        build: .
        links:
            - "database:dockerdb"
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - ./:/code
        ports:
            - '8000:8000'
        environment: 
            - DATABASE_URL=postgres://postgres:postgres@dockerdb:5432/voluntarios
        depends_on:
            - database
        env_file:
            - .env
